<a href="https://colab.research.google.com/github/chandrasekhaar/chandrasekhaar/blob/main/Numpy_B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#what is numpy?


#how many types of arrays are their?
#1d
#2d
#3d

In [ ]:
#scikit learn
#matpltolib
#pandas

#what are different types of usecases and operations achieved easily by numpy
   1) dot product/inner product
   2) matrix multiplication
   3) inverse
   4) linear algebra
   5) random number generation
   6) statistics

In [ ]:
#installation
!pip install numpy

In [ ]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
#difference b/w array&list?
"""array:- array can take homogenous data types
            array's faster than list
            array,s having fixed memory"""


central object is array

In [ ]:
from re import A
a=np.array([1,2,3,4])
print(a)
#want to know shape of the array
a.shape
#want to know the datatype of the array
a.dtype
#want to know dimension of array
a.ndim
#want to know size/number of elements in array
a.size
#want to know size in bytes of each element
A

[1 2 3 4]


In [12]:
import numpy as np
b=np.array([1,2,3,4])
print(b[0])
b[0]=6
print(b)
#element wise math operations
c=np.array([1,2,3,4])
print(b+c)
print(b*c)
#arthematic operations
#sum of elements in an array
print(b.sum())
#minimum value in array
print(b.min())
#maximum value in array
print(b.max())


1
[6 2 3 4]
[7 4 6 8]
[ 6  4  9 16]


Array VS list


In [15]:
l=[2,3,4]
#create an array from list
d=np.array(l)
print(d)
##  list we can add elements
##  Array we cannot add elements
#broad casting mehtod adding elements to the existing array?
a1=d+np.array([5])
print(a1)

[2 3 4]
[7 8 9]


In [17]:
#vector addition:-adding 2 arrays with same size/number of elements
'''v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1+v2)'''

[5 7 9]


In [19]:
l=[2,3,4]
l1=[5,6,7]
print(l+l1)

[2, 3, 4, 5, 6, 7]


In [23]:
#array multiplication
a=np.array([1,2,3,4])
a4=a*3
print(a4)
#find sqrt of numpy aray?
print(np.sqrt(a))

[ 3  6  9 12]
[1.         1.41421356 1.73205081 2.        ]
