<a href="https://colab.research.google.com/github/chandrasekhaar/chandrasekhaar/blob/main/Numpy_B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#what is numpy?


#how many types of arrays are their?
#1d
#2d
#3d

In [ ]:
#scikit learn
#matpltolib
#pandas

#what are different types of usecases and operations achieved easily by numpy
   1. dot product/inner product
   2. matrix multiplication
   3) inverse
   4) linear algebra
   5) random number generation
   6) statistics

In [ ]:
#installation
!pip install numpy

In [ ]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
#difference b/w array&list?
"""array:- array can take homogenous data types
            array's faster than list
            array,s having fixed memory"""


central object is array

In [ ]:
from re import A
a=np.array([1,2,3,4])
print(a)
#want to know shape of the array
a.shape
#want to know the datatype of the array
a.dtype
#want to know dimension of array
a.ndim
#want to know size/number of elements in array
a.size
#want to know size in bytes of each element
A

[1 2 3 4]


In [ ]:
import numpy as np
b=np.array([1,2,3,4])
print(b[0])
b[0]=6
print(b)
#element wise math operations
c=np.array([1,2,3,4])
print(b+c)
print(b*c)
#arthematic operations
#sum of elements in an array
print(b.sum())
#minimum value in array
print(b.min())
#maximum value in array
print(b.max())


1
[6 2 3 4]
[7 4 6 8]
[ 6  4  9 16]


Array VS list


In [ ]:
l=[2,3,4]
#create an array from list
d=np.array(l)
print(d)
##  list we can add elements
##  Array we cannot add elements
#broad casting mehtod adding elements to the existing array?
a1=d+np.array([5])
print(a1)

[2 3 4]
[7 8 9]


In [ ]:
#vector addition:-adding 2 arrays with same size/number of elements
'''v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1+v2)'''

[5 7 9]


In [ ]:
l=[2,3,4]
l1=[5,6,7]
print(l+l1)

[2, 3, 4, 5, 6, 7]


In [ ]:
#array multiplication
a=np.array([1,2,3,4])
a4=a*3
print(a4)
#find sqrt of numpy aray?
print(np.sqrt(a))

[ 3  6  9 12]
[1.         1.41421356 1.73205081 2.        ]


Dot products

In [ ]:
import numpy as np
a=np.array([1,2])
b=np.array([5,6])
#sum of the product of corresponding entries
print(np.dot(a,b))
#multiply each corresponding element and sum
dot=0
for i in range(len(a)):
  dot+=a[i]*b[i]#dot=dot+([a[i]*b[i]])
  print(dot)

17
5
17


In [ ]:
#easy with numpy
dot=np.dot(a,b)
print(dot)

17


In [ ]:
#manual method
c=a*b
print(c)
d=np.sum(c)
print(d)


[ 5 12]
17


In [ ]:
## what is dot means?
#multiply the corresponding elements after that we are doing additon.
dot=a.dot(b)
print(dot)

17


In [ ]:
#new version of dot product
dot=a@b
print(dot)

17


speed test array VS List.


In [5]:
#import time calcaulatornto see the variations
from timeit import default_timer as timer

#create random array
a= np.random.randn(1000)
b= np.random.randn(1000)
#convert these array into list with different variabbles
c=list(a)
d=list(b)
t=1000
def dot1():
  dot=0
  for i in range(len(a)):
    dot+=a[i]*b[i]
    return dot
def dot2():
  return np.dot(a,b)
  #take the timer
  start=timer()
for i in range(t):
    dot1()
end = timer()
t1=end-start
start=timer()
for i in range(t):
    dot2()
end = timer()
t2= end-start
print('time with list:',t1)
print('time with lists:',t2)
print('ratio',t1/t2)




NameError: name 'np' is not defined

dimensional

In [6]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
print(a[0])
#if u want to access particular value from particualar column amd row?
print(a[0,2])
#access from "5" from the above array?
print(a[1,1])
print(a[1][1])

[1 2 3]
3
5
5


slicing

In [12]:
print(a[:,0]) # to know all valuse in 1st column
print(a[0,:]) # to know all values in 1st row

[1 4]
[1 2 3]


In [15]:
#print(a)
print(a.shape)
#transpose rows into column & column into rows
#print(a.T)
k=a.T
print(k)
print(k.shape)

(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


#matrix multiplication

In [20]:
a =np.array([[1,2],[3,4]])
b=np.array([[1,2],[2,3]])
k=a.dot(b)
print(k)
#element wise multiplication
#print(a*b)

[[ 5  8]
 [11 18]]


In [21]:
e=np.array([[1,2,3],[4,5,6]])
print(e)

[[1 2 3]
 [4 5 6]]


In [22]:
#detrerminent:- [(1x4)-(2x3)] we need cross multiplication
a=np.array([[1,2],[3,4]])
c=np.linalg.det(a)
print(c)


-2.0000000000000004


In [23]:
#inverse:-
a=np.array([[1,2],[3,4]])
d=np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
#diagonal
c =np.diag(a)
print(c)


[1 4]


In [27]:
#diagonal an a vector returns diagonal matrix
c=np.diag([1,4])
print(c)

[[1 0]
 [0 4]]
