<a href="https://colab.research.google.com/github/chandrasekhaar/chandrasekhaar/blob/main/PRACTICE_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:
a=np.array([1,2,3])
print(a)
print(a[1])
b=np.array([2,0,2])
print(a+b)
print(a*b)

[1 2 3]
2
[3 2 5]
[2 0 6]


In [6]:
c=np.dot(a,b)
print(c)

8


In [12]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a[0,:])
print(a[:,0])

[[1 2]
 [3 4]]
(2, 2)
[1 2]
[1 3]


In [18]:
import numpy as np
k=np.array([[1,2,3],[4,5,6]])
print(k.shape)
b=a.T
print(b.shape)

(2, 3)
(2, 2)


In [6]:
import numpy as np
a = np.array([[1,2],[2,2]])
b = np.array([[3,4],[5,6]])
z= a.dot(b)
print(z)


[[13 16]
 [16 20]]


In [8]:
k=np.array([[1,4],[1,6]])
print(k)
p=k.dot(b)
print(p)


[[1 4]
 [1 6]]
[[23 28]
 [33 40]]


In [9]:
i=np.array ([[2,4],[6,8]])
print(i)
c= np.linalg.det(i)
print(c)

[[2 4]
 [6 8]]
-8.000000000000002


In [10]:
t=np.diag([1,2,3])
print(t)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
y=a[0:3,1:2]
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [16]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]


In [17]:
bool_index = (a>2)
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


In [19]:
a = np.array([10,19,30,41,50,61])
k=np.argwhere (a%2==0).flatten()
print(k)
print(a[k])

[0 2 4]
[10 30 50]


In [33]:
a= np.arange (1,10)
print(a)
b=a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
